<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2 (Python 3.10.8 on win32)" generated="20230601 04:47:14.869" rpa="false">
<suite id="s1" name="Locators" source="C:\Users\sriha\PycharmProjects\Firstrobo\tests\locators.robot">
<test id="s1-t1" name="Learining Locators">
<kw name="open browser">
<arguments>
<arg>https://stackoverflow.com/questions/46812155/how-to-run-headless-remote-chrome-using-robot-framework</arg>
<arg>headlesschrome</arg>
</arguments>
<msg timestamp="20230601 04:47:14.944" level="FAIL">No keyword with name 'open browser' found.</msg>
<status status="FAIL" starttime="20230601 04:47:14.944" endtime="20230601 04:47:14.945"></status>
</kw>
<status status="FAIL" starttime="20230601 04:47:14.940" endtime="20230601 04:47:14.945" critical="yes">No keyword with name 'open browser' found.</status>
</test>
<status status="FAIL" starttime="20230601 04:47:14.876" endtime="20230601 04:47:14.947"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Locators">Locators</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230601 04:47:14.934" level="ERROR">Error in file 'C:\Users\sriha\PycharmProjects\Firstrobo\tests\locators.robot' on line 2: Importing test library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Flask\venv\Scripts\robot.exe
  C:\Users\sriha\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\sriha\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\sriha\AppData\Local\Programs\Python\Python310\lib
  C:\Users\sriha\AppData\Local\Programs\Python\Python310
  C:\Flask\venv
  C:\Flask\venv\lib\site-packages</msg>
</errors>
</robot>
